# Generated by Django 5.0.1 on 2024-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hotel_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='banner_image',
            field=models.ImageField(upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotel'),
        ),
    ]
